version: '3.8'

services:
  cogniflow:
    build: .
    ports:
      - "8000:8000"
    container_name: cogniflow-app
    restart: unless-stopped
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8000 